knp_paginator:
    page_range: 5
    default_options:
        page_name: page
        sort_field_name: sort
        sort_direction_name: dir
        filter_field_name: search_in
        filter_value_name: q
    template:
        pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig'
