# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\GeminiService:
        autowire: true

    App\Service\PaymentPredictionService:
        autowire: true
        arguments:
            $apiKey: '%env(GROQ_API_KEY)%'

    App\Service\StripeService:
        arguments:
            $secretKey: '%env(STRIPE_SECRET_KEY)%'

    App\Service\CurrencyExchangeService:
        autowire: true

    App\Service\CloudinaryStorageService:
        arguments:
            $cloudName: '%env(default::CLOUDINARY_CLOUD_NAME)%'
            $apiKey: '%env(default::CLOUDINARY_API_KEY)%'
            $apiSecret: '%env(default::CLOUDINARY_API_SECRET)%'
            $uploadPreset: '%env(default::CLOUDINARY_UPLOAD_PRESET)%'
